# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "2048"
     vb.customize [
       "modifyvm", :id,
       "--vram", "1024",
       "--clipboard", "bidirectional",
       "--draganddrop", "bidirectional",
       "--cpus", "4",
       "--ioapic", "on"
     ]
  end
end

