apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sample
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
      - name: nginx
        image: nginx
