name: cloud-run-cloud-deploy-pipeline

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cloud-run-cloud-deploy-pipeline.yaml
      - gcp/cloud-run/cloud-deploy.yaml

permissions:
  contents: read
  id-token: write

jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment:
      name: main
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "github-actions@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

      - uses: google-github-actions/setup-gcloud@v2

      - run: |
          gcloud deploy apply --file gcp/cloud-run/cloud-deploy.yaml --region asia-northeast1

  deploy:
    needs: pipeline
    uses: ./.github/workflows/cloud-run-cloud-deploy.yaml
