name: cloud-run-cloud-deploy

on:
  push:
    branches:
      - add-cloud-run-cloude-deploy
    paths:
      - .github/workflows/cloud-run-cloud-deploy.yaml
      - .github/reusable_workflows/cloud-run-cloud-deploy.yaml
      - gcp/cloud-run/**
      - '!gcp/cloud-run/cloud-deploy.yaml'

jobs:
  deploy:
    uses: ./.github/reusable_workflows/cloud-run-cloud-deploy.yaml
    with:
      called_by: deploy
