name: cloud-run-cloud-deploy

on:
  push:
    branches:
      - add-cloud-run-cloude-deploy
    paths:
      - .github/workflows/cloud-run-cloud-deploy.yaml
      - gcp/cloud-run/**
      - '!gcp/cloud-run/cloud-deploy.yaml'
  workflow_call:
    inputs:
      called_by:
        description: "Release name prefix"
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: main
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "github-actions@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Set short git commit SHA
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - uses: google-github-actions/create-cloud-deploy-release@v1
        with:
          name: ${{ inputs.called_by || "deploy" }}-${{ env.COMMIT_SHORT_SHA }}
          delivery_pipeline: cloud-run-cloud-deploy
          region: asia-northeast1
          skaffold_file: gcp/cloud-run/scaffold.yaml
          images: |
            nginx=nginx
