name: docker-build-cache

on:
  push:
    branches:
      - main
      - add-docker-build-cache
    paths:
      - .github/workflows/docker-build-cache.yaml
      - github-actions/docker-build-cache
defaults:
  runs:
    working-directory: github-actions/docker-build-cache

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Set metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: asia-northeast1-docker.pkg.dev
          tags: |
            type=semver,pattern={{raw}}
            type=sha,format=short

      - name: Build
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: false
          tags: ${{ steps.metadata.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
